# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74fa8e05117a29b49a7b9962d835371e0e83e8e92dd3451e1e56c98099e2a52c812ecdaf00d9ad4d54d07b1e02ccb855cb16488ed6ac53a4b550557a1282d4c5

test:
  secret_key_base: 2e8c9f7ca175c36d546f2d9508dd36bf849ae1d08ba83130a64e8f8f801d475291f4d86b70a8a7b8fcf2c76a8c23dec9d3e9b46291f586795314f8f2d7fe5cc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
